### PR TITLE
NVDLA HW updates

### PR DESCRIPTION
**Pull request by tymcauley**
Summary:
* Bump NVDLA hardware submodule to master branch, and regenerated RTL from there. Note that this didn't result in any functional RTL changes, but it does mean we can now generate RTL from other NVDLA configs
* Fix bugs in NVDLA RTL generation script
* Refactor NVDLA configuration Chisel logic
* Set NVDLA AXI address bus width in Chisel

### CODE REVIEW

**Comment by tymcauley** [comment]
@abejgonzalez just wanted to make sure you saw this PR.

**Comment by abejgonzalez** [comment]
@tymcauley I must have missed this. By chance do you remember if this booted Linux / worked on Linux? The simple regressions Chipyard seems to work. I am a bit hesitant to merge this because I think the `nvdlav1` branch seemed to be more stable in the past (but maybe I am just misremembering).

**Comment by abejgonzalez** [comment]
It also looks like you haven't updated the `vsrc.mk` and `Makefile` so that this works under Verilator in Chipyard (I see a lot of unresolved modules that need to be added).

**Comment by tymcauley** [comment]
No problem! Ya, I can't really recall the state of this PR. It's been a long time since I looked at the NVDLA stuff, so I probably won't be able to do much testing on this. Keeping with the `nvdlav1` branch seems like a fair move. I'd be fine with closing this PR.

**Comment by abejgonzalez** [comment]
Sorry for being so late on this and missing this. I'll post an issue just in case someone wants to do this in the future.

**Comment by tymcauley** [comment]
No worries! And that sounds like a fine resolution.

**Pull request closed without merging**
